name: Demo workflow
on:
    pull_request:
        types:
            - opened
        branches:
            - master
    workflow_dispatch:
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: outputjobinfo
              run: echo "${{ toJSON(github.event) }}"
            - name: Get code
              uses: actions/checkout@v4
            - name: install dependencies
              run: |
                python3 -m pip install --upgrade pip
                pip install flask
            - name: Test code
              run: python3 test_app.py
            - name: Run code
              run: python3 app.py &
            - name: Deploy
              run: echo "Deploying..."
             